/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUIAufgabe04.java
 *
 * Created on 17.11.2011, 11:40:41
 */
package se.edu.gui.aufgabe04;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField.AbstractFormatter;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author steeb
 */
public class GUIAufgabe04 extends javax.swing.JFrame {

    /** Creates new form GUIAufgabe04 */
    public GUIAufgabe04() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblFlaschengroesse = new javax.swing.JLabel();
        lblFlaschenpreis = new javax.swing.JLabel();
        lblPreisProL = new javax.swing.JLabel();
        flaschengroesse = new javax.swing.JComboBox();
        btnUmrechnenDown = new javax.swing.JButton();
        btnUmrechnenUp = new javax.swing.JButton();
        lblEuro0 = new javax.swing.JLabel();
        lblEuro1 = new javax.swing.JLabel();
        ftfFlaschenpreis = new javax.swing.JFormattedTextField();
        ftfPreisProL = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblFlaschengroesse.setText("Flaschengröße:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(lblFlaschengroesse, gridBagConstraints);

        lblFlaschenpreis.setText("Flaschenpreis:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(lblFlaschenpreis, gridBagConstraints);

        lblPreisProL.setText("Preis pro L:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(lblPreisProL, gridBagConstraints);

        flaschengroesse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0,187l", "0,25l", "0,375l", "0,5l", "0,62l", "0,75l", "0,8l", "1l", "1,5l" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(flaschengroesse, gridBagConstraints);

        btnUmrechnenDown.setText("↓");
        btnUmrechnenDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUmrechnenDownActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(btnUmrechnenDown, gridBagConstraints);

        btnUmrechnenUp.setText("↑");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(btnUmrechnenUp, gridBagConstraints);

        lblEuro0.setText("€");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        getContentPane().add(lblEuro0, gridBagConstraints);

        lblEuro1.setText("€");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        getContentPane().add(lblEuro1, gridBagConstraints);

        ftfFlaschenpreis.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        ftfFlaschenpreis.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ftfFlaschenpreis.setText("0,00");
        ftfFlaschenpreis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ftfFlaschenpreisKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(ftfFlaschenpreis, gridBagConstraints);
        ((NumberFormatter)ftfFlaschenpreis.getFormatter()).setAllowsInvalid(false);

        ftfPreisProL.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        ftfPreisProL.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ftfPreisProL.setText("0,00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(ftfPreisProL, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUmrechnenDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUmrechnenDownActionPerformed
        double flaschenpreis;
        AbstractFormatter formatter = ftfFlaschenpreis.getFormatter();
        try {
            flaschenpreis = Double.parseDouble(formatter.stringToValue(ftfFlaschenpreis.getText()).toString());
            ftfPreisProL.setValue(formatter.stringToValue((flaschenpreis * 10) + ""));
        } catch (ParseException ex) {
            Logger.getLogger(GUIAufgabe04.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUmrechnenDownActionPerformed

    private void ftfFlaschenpreisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftfFlaschenpreisKeyTyped
        ftfFlaschenpreis.getText().matches("\\d{1,3}(\\.?\\d{3})*(,\\d{1,2})?");
    }//GEN-LAST:event_ftfFlaschenpreisKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new GUIAufgabe04().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUmrechnenDown;
    private javax.swing.JButton btnUmrechnenUp;
    private javax.swing.JComboBox flaschengroesse;
    private javax.swing.JFormattedTextField ftfFlaschenpreis;
    private javax.swing.JFormattedTextField ftfPreisProL;
    private javax.swing.JLabel lblEuro0;
    private javax.swing.JLabel lblEuro1;
    private javax.swing.JLabel lblFlaschengroesse;
    private javax.swing.JLabel lblFlaschenpreis;
    private javax.swing.JLabel lblPreisProL;
    // End of variables declaration//GEN-END:variables
}
